// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	user "github.com/lishaonian/apps/service/user/api/internal/handler/user"
	"github.com/lishaonian/apps/service/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user/getUser/:id",
				Handler: user.GetUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/updateUser",
				Handler: user.UpdateUserHandler(serverCtx),
			},
		},
	)
}
