// Code generated by goctl. DO NOT EDIT.
package types

type UserReq struct {
	Id int64 `path:"id"`
}

type UserResp struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
	Age  int64  `json:"age"`
}

type UserUpdateReq struct {
	Id   int64  `form:"id"`
	Name string `form:"name"`
}
